### ISSUE TITLE
Feature: User can view a  list of the top 10 selling books for a given week.

### ISSUE THREAD

**Issue by Steve-A-Dore** [Steve-A-Dore/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can view a list of the top 10 selling books for a given week.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When the user opens the application, they will view a list of the top 10 selling books.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] There will be a date field allowing the user to change the week the user searches through.
- [ ] Each book will populate through a card.
- [ ] Each card will contain the following:
  - [ ] Book title
  - [ ] Author
  - [ ] Publisher
  - [ ] Current Rank - for the week.
  - [ ] Published Date.
- [ ] The Main Page Will Display 5 cards.
- [ ] There will be a carousel that will allow the user to:
  - [ ] Pivot forward to the next set of 5.
  - [ ] Pivot back to the previous set of 5.
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
