### ISSUE TITLE
Feature: User can choose which type of search they want to search for books

### ISSUE THREAD

**Issue by Steve-A-Dore** [Steve-A-Dore/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] User can choose which type of search they want to search for books.
       - [ ] By Category
       - [ ] By Author 
- [ ] 
- [ ] 
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by Steve-A-Dore** [comment]
There is still one issue with this code that I was unable to resolve. If the user doesn't type in their search string in the correct shape - so 'Cormac McCarthy ' or "Hardcover Fiction" - that is to say two strings with a space inbetween, than the search will still attempt to search and will return no results, and will then bring the user to the results page except there will be _no_ cards on the page and the results page will be empty. I attempted a number of attempts to fix this, but was unable to do so.
